// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: netmessage.proto

#include "netmessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace google {
namespace protobuf {
class HelloMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<HelloMsg>
      _instance;
} _HelloMsg_default_instance_;
class VersionMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VersionMsg>
      _instance;
} _VersionMsg_default_instance_;
class VerAckMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VerAckMsg>
      _instance;
} _VerAckMsg_default_instance_;
class AddrMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AddrMsg>
      _instance;
} _AddrMsg_default_instance_;
class GetAddrMsgDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetAddrMsg>
      _instance;
} _GetAddrMsg_default_instance_;
}  // namespace protobuf
}  // namespace google
namespace protobuf_netmessage_2eproto {
void InitDefaultsHelloMsgImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::google::protobuf::_HelloMsg_default_instance_;
    new (ptr) ::google::protobuf::HelloMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::HelloMsg::InitAsDefaultInstance();
}

void InitDefaultsHelloMsg() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsHelloMsgImpl);
}

void InitDefaultsVersionMsgImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::google::protobuf::_VersionMsg_default_instance_;
    new (ptr) ::google::protobuf::VersionMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::VersionMsg::InitAsDefaultInstance();
}

void InitDefaultsVersionMsg() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsVersionMsgImpl);
}

void InitDefaultsVerAckMsgImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::google::protobuf::_VerAckMsg_default_instance_;
    new (ptr) ::google::protobuf::VerAckMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::VerAckMsg::InitAsDefaultInstance();
}

void InitDefaultsVerAckMsg() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsVerAckMsgImpl);
}

void InitDefaultsAddrMsgImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::google::protobuf::_AddrMsg_default_instance_;
    new (ptr) ::google::protobuf::AddrMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::AddrMsg::InitAsDefaultInstance();
}

void InitDefaultsAddrMsg() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsAddrMsgImpl);
}

void InitDefaultsGetAddrMsgImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::google::protobuf::_GetAddrMsg_default_instance_;
    new (ptr) ::google::protobuf::GetAddrMsg();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::GetAddrMsg::InitAsDefaultInstance();
}

void InitDefaultsGetAddrMsg() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGetAddrMsgImpl);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::HelloMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::HelloMsg, msg_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::VersionMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::VerAckMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::AddrMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::AddrMsg, addrlist_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::GetAddrMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::google::protobuf::HelloMsg)},
  { 6, -1, sizeof(::google::protobuf::VersionMsg)},
  { 11, -1, sizeof(::google::protobuf::VerAckMsg)},
  { 16, -1, sizeof(::google::protobuf::AddrMsg)},
  { 22, -1, sizeof(::google::protobuf::GetAddrMsg)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::_HelloMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::_VersionMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::_VerAckMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::_AddrMsg_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::_GetAddrMsg_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "netmessage.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020netmessage.proto\022\017google.protobuf\"\027\n\010H"
      "elloMsg\022\013\n\003msg\030\001 \001(\t\"\014\n\nVersionMsg\"\013\n\tVe"
      "rAckMsg\"\033\n\007AddrMsg\022\020\n\010addrList\030\001 \003(\t\"\014\n\n"
      "GetAddrMsgb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 138);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "netmessage.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_netmessage_2eproto
namespace google {
namespace protobuf {

// ===================================================================

void HelloMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HelloMsg::kMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HelloMsg::HelloMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_netmessage_2eproto::InitDefaultsHelloMsg();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.HelloMsg)
}
HelloMsg::HelloMsg(const HelloMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msg().size() > 0) {
    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  // @@protoc_insertion_point(copy_constructor:google.protobuf.HelloMsg)
}

void HelloMsg::SharedCtor() {
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

HelloMsg::~HelloMsg() {
  // @@protoc_insertion_point(destructor:google.protobuf.HelloMsg)
  SharedDtor();
}

void HelloMsg::SharedDtor() {
  msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void HelloMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HelloMsg::descriptor() {
  ::protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const HelloMsg& HelloMsg::default_instance() {
  ::protobuf_netmessage_2eproto::InitDefaultsHelloMsg();
  return *internal_default_instance();
}

HelloMsg* HelloMsg::New(::google::protobuf::Arena* arena) const {
  HelloMsg* n = new HelloMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HelloMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.HelloMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool HelloMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.HelloMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string msg = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msg().data(), static_cast<int>(this->msg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.HelloMsg.msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.HelloMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.HelloMsg)
  return false;
#undef DO_
}

void HelloMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.HelloMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string msg = 1;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), static_cast<int>(this->msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.HelloMsg.msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->msg(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.HelloMsg)
}

::google::protobuf::uint8* HelloMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.HelloMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string msg = 1;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), static_cast<int>(this->msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.HelloMsg.msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->msg(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.HelloMsg)
  return target;
}

size_t HelloMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.HelloMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string msg = 1;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HelloMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.HelloMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const HelloMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const HelloMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.HelloMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.HelloMsg)
    MergeFrom(*source);
  }
}

void HelloMsg::MergeFrom(const HelloMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.HelloMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.msg().size() > 0) {

    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
}

void HelloMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.HelloMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HelloMsg::CopyFrom(const HelloMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.HelloMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HelloMsg::IsInitialized() const {
  return true;
}

void HelloMsg::Swap(HelloMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HelloMsg::InternalSwap(HelloMsg* other) {
  using std::swap;
  msg_.Swap(&other->msg_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HelloMsg::GetMetadata() const {
  protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void VersionMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VersionMsg::VersionMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_netmessage_2eproto::InitDefaultsVersionMsg();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.VersionMsg)
}
VersionMsg::VersionMsg(const VersionMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:google.protobuf.VersionMsg)
}

void VersionMsg::SharedCtor() {
  _cached_size_ = 0;
}

VersionMsg::~VersionMsg() {
  // @@protoc_insertion_point(destructor:google.protobuf.VersionMsg)
  SharedDtor();
}

void VersionMsg::SharedDtor() {
}

void VersionMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* VersionMsg::descriptor() {
  ::protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VersionMsg& VersionMsg::default_instance() {
  ::protobuf_netmessage_2eproto::InitDefaultsVersionMsg();
  return *internal_default_instance();
}

VersionMsg* VersionMsg::New(::google::protobuf::Arena* arena) const {
  VersionMsg* n = new VersionMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void VersionMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.VersionMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool VersionMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.VersionMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.VersionMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.VersionMsg)
  return false;
#undef DO_
}

void VersionMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.VersionMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.VersionMsg)
}

::google::protobuf::uint8* VersionMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.VersionMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.VersionMsg)
  return target;
}

size_t VersionMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.VersionMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void VersionMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.VersionMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const VersionMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VersionMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.VersionMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.VersionMsg)
    MergeFrom(*source);
  }
}

void VersionMsg::MergeFrom(const VersionMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.VersionMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void VersionMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.VersionMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VersionMsg::CopyFrom(const VersionMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.VersionMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VersionMsg::IsInitialized() const {
  return true;
}

void VersionMsg::Swap(VersionMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VersionMsg::InternalSwap(VersionMsg* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata VersionMsg::GetMetadata() const {
  protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void VerAckMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VerAckMsg::VerAckMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_netmessage_2eproto::InitDefaultsVerAckMsg();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.VerAckMsg)
}
VerAckMsg::VerAckMsg(const VerAckMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:google.protobuf.VerAckMsg)
}

void VerAckMsg::SharedCtor() {
  _cached_size_ = 0;
}

VerAckMsg::~VerAckMsg() {
  // @@protoc_insertion_point(destructor:google.protobuf.VerAckMsg)
  SharedDtor();
}

void VerAckMsg::SharedDtor() {
}

void VerAckMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* VerAckMsg::descriptor() {
  ::protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VerAckMsg& VerAckMsg::default_instance() {
  ::protobuf_netmessage_2eproto::InitDefaultsVerAckMsg();
  return *internal_default_instance();
}

VerAckMsg* VerAckMsg::New(::google::protobuf::Arena* arena) const {
  VerAckMsg* n = new VerAckMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void VerAckMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.VerAckMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool VerAckMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.VerAckMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.VerAckMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.VerAckMsg)
  return false;
#undef DO_
}

void VerAckMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.VerAckMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.VerAckMsg)
}

::google::protobuf::uint8* VerAckMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.VerAckMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.VerAckMsg)
  return target;
}

size_t VerAckMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.VerAckMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void VerAckMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.VerAckMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const VerAckMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VerAckMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.VerAckMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.VerAckMsg)
    MergeFrom(*source);
  }
}

void VerAckMsg::MergeFrom(const VerAckMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.VerAckMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void VerAckMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.VerAckMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VerAckMsg::CopyFrom(const VerAckMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.VerAckMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VerAckMsg::IsInitialized() const {
  return true;
}

void VerAckMsg::Swap(VerAckMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VerAckMsg::InternalSwap(VerAckMsg* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata VerAckMsg::GetMetadata() const {
  protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void AddrMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AddrMsg::kAddrListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AddrMsg::AddrMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_netmessage_2eproto::InitDefaultsAddrMsg();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.AddrMsg)
}
AddrMsg::AddrMsg(const AddrMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      addrlist_(from.addrlist_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:google.protobuf.AddrMsg)
}

void AddrMsg::SharedCtor() {
  _cached_size_ = 0;
}

AddrMsg::~AddrMsg() {
  // @@protoc_insertion_point(destructor:google.protobuf.AddrMsg)
  SharedDtor();
}

void AddrMsg::SharedDtor() {
}

void AddrMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AddrMsg::descriptor() {
  ::protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AddrMsg& AddrMsg::default_instance() {
  ::protobuf_netmessage_2eproto::InitDefaultsAddrMsg();
  return *internal_default_instance();
}

AddrMsg* AddrMsg::New(::google::protobuf::Arena* arena) const {
  AddrMsg* n = new AddrMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void AddrMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.AddrMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  addrlist_.Clear();
  _internal_metadata_.Clear();
}

bool AddrMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.AddrMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string addrList = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_addrlist()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->addrlist(this->addrlist_size() - 1).data(),
            static_cast<int>(this->addrlist(this->addrlist_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.AddrMsg.addrList"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.AddrMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.AddrMsg)
  return false;
#undef DO_
}

void AddrMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.AddrMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string addrList = 1;
  for (int i = 0, n = this->addrlist_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->addrlist(i).data(), static_cast<int>(this->addrlist(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.AddrMsg.addrList");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->addrlist(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.AddrMsg)
}

::google::protobuf::uint8* AddrMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.AddrMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string addrList = 1;
  for (int i = 0, n = this->addrlist_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->addrlist(i).data(), static_cast<int>(this->addrlist(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.AddrMsg.addrList");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->addrlist(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.AddrMsg)
  return target;
}

size_t AddrMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.AddrMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string addrList = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->addrlist_size());
  for (int i = 0, n = this->addrlist_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->addrlist(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AddrMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.AddrMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const AddrMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AddrMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.AddrMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.AddrMsg)
    MergeFrom(*source);
  }
}

void AddrMsg::MergeFrom(const AddrMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.AddrMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  addrlist_.MergeFrom(from.addrlist_);
}

void AddrMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.AddrMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AddrMsg::CopyFrom(const AddrMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.AddrMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddrMsg::IsInitialized() const {
  return true;
}

void AddrMsg::Swap(AddrMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AddrMsg::InternalSwap(AddrMsg* other) {
  using std::swap;
  addrlist_.InternalSwap(&other->addrlist_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata AddrMsg::GetMetadata() const {
  protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetAddrMsg::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetAddrMsg::GetAddrMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_netmessage_2eproto::InitDefaultsGetAddrMsg();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.GetAddrMsg)
}
GetAddrMsg::GetAddrMsg(const GetAddrMsg& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:google.protobuf.GetAddrMsg)
}

void GetAddrMsg::SharedCtor() {
  _cached_size_ = 0;
}

GetAddrMsg::~GetAddrMsg() {
  // @@protoc_insertion_point(destructor:google.protobuf.GetAddrMsg)
  SharedDtor();
}

void GetAddrMsg::SharedDtor() {
}

void GetAddrMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GetAddrMsg::descriptor() {
  ::protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetAddrMsg& GetAddrMsg::default_instance() {
  ::protobuf_netmessage_2eproto::InitDefaultsGetAddrMsg();
  return *internal_default_instance();
}

GetAddrMsg* GetAddrMsg::New(::google::protobuf::Arena* arena) const {
  GetAddrMsg* n = new GetAddrMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GetAddrMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.GetAddrMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_metadata_.Clear();
}

bool GetAddrMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.GetAddrMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, _internal_metadata_.mutable_unknown_fields()));
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.GetAddrMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.GetAddrMsg)
  return false;
#undef DO_
}

void GetAddrMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.GetAddrMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.GetAddrMsg)
}

::google::protobuf::uint8* GetAddrMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.GetAddrMsg)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.GetAddrMsg)
  return target;
}

size_t GetAddrMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.GetAddrMsg)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GetAddrMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.GetAddrMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const GetAddrMsg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetAddrMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.GetAddrMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.GetAddrMsg)
    MergeFrom(*source);
  }
}

void GetAddrMsg::MergeFrom(const GetAddrMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.GetAddrMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

}

void GetAddrMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.GetAddrMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetAddrMsg::CopyFrom(const GetAddrMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.GetAddrMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetAddrMsg::IsInitialized() const {
  return true;
}

void GetAddrMsg::Swap(GetAddrMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetAddrMsg::InternalSwap(GetAddrMsg* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GetAddrMsg::GetMetadata() const {
  protobuf_netmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_netmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
